highlight djangoTagBlock guifg=cyan gui=NONE
highlight djangoVarBlock guifg=white gui=NONE
highlight djangoStatement guifg=gray gui=NONE
highlight djangoFilter guifg=purple gui=NONE
highlight djangoArgument guifg=green gui=NONE
highlight djangoTagError guifg=red gui=NONE
highlight djangoVarError guifg=red gui=NONE
highlight djangoError guifg=blue gui=NONE
highlight djangoComment guifg=yellow gui=NONE
highlight djangoComBlock guifg=yellow gui=NONE
highlight djangoTodo guifg=yellow gui=NONE
